# Generated by Django 4.0.3 on 2022-03-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='subject',
        ),
    ]
