# Generated by Django 4.0.3 on 2022-03-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
