# Generated by Django 4.0.3 on 2022-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
