# Generated by Django 4.0.3 on 2022-04-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
