# Generated by Django 4.0.3 on 2022-04-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
    ]
